apiVersion: v1
kind: Service
metadata:
  name: uswa-app-service
  namespace: scd
spec:
  type: NodePort
  selector:
    app: uswa-app
  ports:
    - port: 80               # Exposed service port
      targetPort: 5173       # Port inside the frontend container
      nodePort: 30010
      # External access via Minikube
